# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
   branches: [ "main" ]
  pull_request:
   branches: [ "main" ]
  workflow_dispatch:
jobs:
 Logintodockerhub:
  runs-on: ubuntu-latest
  environment: Dev
  steps:
   - uses: actions/checkout@v3
   - name: docker login
     uses: docker/login-action@v2.1.0
     with:
      registry: registry-1.docker.io
      username: ${{secrets.DOCKERHUBUSERNAME}}
      password: ${{secrets.DOCKERHUBPASSWORD}}
 
 
 Log-into-dockerhub:
  runs-on: ubuntu-latest
  environment: Qa
  steps:
   - uses: actions/checkout@v3
   - name: docker login
     uses: docker/login-action@v2.1.0
     with:
      registry: registry-1.docker.io
      username: ${{secrets.DOCKERHUBUSERNAME}}
      password: ${{secrets.DOCKERHUBPASSWORD}}

